### ISSUE TITLE
some figures not showing up with " .. figure:: "

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#16]
![screenshot from 2018-09-03 13-52-54](https://user-images.githubusercontent.com/20714542/44967291-81ea6980-af83-11e8-9e59-41ef237d28be.png)

amss3.html

**Comment by mmcky** [comment]
here is the source

```
We obtain the following graph for the historgram of the last 100,000 observations on the par value of government debt

  .. figure:: /_static/figures/amss3_g3.png
```

I think the issue here is that the directive for some reason is two spaces into the document. It seems that the ``html`` renderer is more robust with malformed ``rst``. @fkazemian do you know how to compile jupyter notebooks with ``all`` text and code? Would you mind checking if this is malformed source code in the rst?

**Comment by fkazemian** [comment]
Hi @mmcky , yes I fixed it in PR#17

**Comment by fkazemian** [comment]
Hi @mmcky, At first I checked it locally and then fixed the source.

**Comment by mmcky** [comment]
- [ ] just merged #17 so this should be checked tomorrow (@fkazemian)

**Comment by fkazemian** [comment]
Hi @mmcky , It is fixed. I change the label to `fixed`.
![screenshot from 2018-09-21 10-58-03](https://user-images.githubusercontent.com/20714542/45854229-504c0d80-bd8d-11e8-9f3f-bfa9be764bf2.png)

**Comment by mmcky** [comment]
thanks @fkazemian
