### ISSUE TITLE
In the lecture  "Job Search II: Search and Separation", using @njit makes the code really slow

### ISSUE THREAD

**Issue by Alalalalaki** [QuantEcon/lecture-source-py#271]
It is way faster without @njit in both u(c, σ) and Q(v, h).

![image](https://user-images.githubusercontent.com/31154974/58005389-87431080-7b20-11e9-894e-eea85d188987.png)

**Comment by jstac** [comment]
Thanks @Alalalalaki .  We'll check it out.

@shizejin Would you mind to take a look?

**Comment by shizejin** [comment]
Thanks @Alalalalaki .

Using `@njit` for `u(c, σ)` should be totally fine.

The main reason that using `@njit` for `Q(v, h)` makes the code so slow is because we put the line `Q = operator_factory(mcm, use_parallel)` inside the `solve_model` function, which means each time we call `solve_model`, `Q(v, h)` will be compiled once and that takes long.

@jstac To increase the speed, we can drop the `operator_factory` function and make `Q(v, h)` takes all the parameters as arguments

```python
@njit
def Q(v, h, α, β, γ, c, σ, w_vals, ϕ_vals):
    """
    A jitted function to update the Bellman equations

    """
    v_new = np.empty_like(v)

    for i in range(len(w_vals)):
        w = w_vals[i]
        v_new[i] = u(w, σ) + β * ((1 - α) * v[i] + α * h)

    h_new = u(c, σ) + β * (1 - γ) * h + \
                    β * γ * np.sum(np.maximum(h, v) * ϕ_vals)

    return v_new, h_new
```

and then use it in `solve_model` as

```python
def solve_model(mcm, use_parallel=True, tol=1e-5, max_iter=2000):
    """
    Iterates to convergence on the Bellman equations

    mcm is an instance of McCallModel
    """

    v = np.ones_like(mcm.w_vals)   # Initial guess of v
    h = 1                          # Initial guess of h
    i = 0
    error = tol + 1

    while error > tol and i < max_iter:
        v_new, h_new = Q(v, h, mcm.α, mcm.β, mcm.γ, mcm.c, mcm.σ, \
                         mcm.w_vals, mcm.ϕ_vals)
        error_1 = np.max(np.abs(v_new - v))
        error_2 = np.abs(h_new - h)
        error = max(error_1, error_2)
        v = v_new
        h = h_new
        i += 1

    return v, h
```

By doing so, the performance of the code is

```python
%%timeit

mcm = McCallModel()
v, h = solve_model(mcm)
```
```
5.81 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

comparing to the case without `@njit`

```
72.9 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

on my computer.

I think `operator_factory` is a very intuitive way to define main operators. On the other hand, when the problem to be solved is so simple, the cost of compilation becomes non-ignorable.

**Comment by jstac** [comment]
I fully agree.  Thanks @Alalalalaki for raising the issue and @shizejin for nice analysis.

@shizejin , would you mind to prepare a PR that makes this change, together with @AnjuJoon 

@AnjuJoon Can you show @shizejin how to check the lectures by using `make` functions in the build system?
