### ISSUE TITLE
An introductory example

### ISSUE THREAD

**Issue by tatsu789** [QuantEcon/lecture-source-py#772]
![image](https://user-images.githubusercontent.com/58211766/69617044-b7e5a300-108b-11ea-8126-a311c7d2e8c8.png)
The first two lines do not correspond to an import

**Comment by tatsu789** [comment]
given that the numpy and plot imports were made in the lecture I believe the graph displays. If this was the first exercise I do not believe that this code will work

**Comment by mmcky** [comment]
hi @tatsu789 -- the lectures are treated in a similar view a jupyter notebook. All code-blocks should be executed sequentially in jupyter kernel. So you are correct this works because of the imports in https://python.quantecon.org/python_by_example.html#Version-1. Each code-block is not self contained but is reliant on previous blocks to be run. 

We often place broader imports at the top of each lecture.

**Comment by tatsu789** [comment]
Hi @mmcky thankyou for the clarification
understood, so I should take it that the "first pair of lines" from the first block when the imports are introduced?
Appologies for the simple question I am just starting out on python

**Comment by mmcky** [comment]
no problem - thanks for checking. 
Yes. To get that to work on its own you would need the imports to get the packages in copy-paste type approach. You can also download the lecture as a notebook if you wish.
